using System;
using System.IO;
using System.Linq;
using Spark.Api.Help;

namespace Spark.Cli.Tests;

/// <summary>
/// <c>spark docs</c> (<c>E12-T5</c>): the help library, listed, printed or written out.
/// </summary>
/// <remarks>
/// <para>
/// <b>What is deliberately not tested here is the content of a page.</b> The node reference is
/// generated by <c>NodeReference</c> and the Markdown by <c>HelpMarkdown.Write</c>, both of which
/// have their own suites — <c>HelpMarkdownWriterTests</c> asserts the round trip over every topic
/// that ships. This covers the verb: its three modes, the exit codes, and the one thing it must not
/// do, which is claim success on a topic it did not find.
/// </para>
/// <para>
/// <b>The library comes from the real composition</b>, not a fixture, because the verb's whole
/// claim is that it writes what the F1 window shows. A test that built its own library would pass
/// on a tree where those two had come apart.
/// </para>
/// </remarks>
public sealed class DocsVerbTests : IDisposable
{
    private readonly string _root;

    public DocsVerbTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "spark-cli-docs", Guid.NewGuid().ToString("n"));
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_root))
            {
                Directory.Delete(_root, recursive: true);
            }
        }
        catch (Exception failure) when (failure is IOException or UnauthorizedAccessException)
        {
            // Left for the operating system; the next run makes its own folder.
        }
    }

    /// <summary>
    /// Bare, it lists every topic and marks which are generated — the distinction a reader of the
    /// list needs, because only the written ones are files anybody can edit.
    /// </summary>
    [Fact]
    public void TheListingNamesEveryTopicAndSaysWhichAreGenerated()
    {
        StringWriter output = new();

        Assert.Equal(0, Program.Docs([], output, new StringWriter()));

        string said = output.ToString();

        Assert.Contains("written    concepts.lacing", said, StringComparison.Ordinal);
        Assert.Contains("generated  nodes.Spark.Nodes.Core/Point.FromCoordinates", said, StringComparison.Ordinal);
        Assert.Contains("generated  nodes.index", said, StringComparison.Ordinal);
        Assert.Contains("written, ", said, StringComparison.Ordinal);
    }

    /// <summary>
    /// <c>--topic</c> prints one page as Markdown, front matter and all, so it can be piped
    /// somewhere or read where it lands.
    /// </summary>
    [Fact]
    public void ATopicIsPrintedAsMarkdown()
    {
        StringWriter output = new();

        Assert.Equal(0, Program.Docs(
            ["--topic", "nodes.Spark.Nodes.Core/Point.FromCoordinates"], output, new StringWriter()));

        string said = output.ToString();

        Assert.StartsWith("---\nid: nodes.Spark.Nodes.Core/Point.FromCoordinates", said, StringComparison.Ordinal);
        Assert.Contains("# Point.FromCoordinates", said, StringComparison.Ordinal);

        // And it is the Markdown the reader understands, which is what makes printing it useful
        // rather than merely readable.
        HelpDocument parsed = HelpMarkdown.Parse(said, "unused");
        Assert.Equal("nodes.Spark.Nodes.Core/Point.FromCoordinates", parsed.Id);
    }

    /// <summary>A hand-written concept topic prints too, from the file it lives in.</summary>
    [Fact]
    public void AWrittenTopicIsPrintedFromItsFile()
    {
        StringWriter output = new();

        Assert.Equal(0, Program.Docs(["--topic", "concepts.lacing"], output, new StringWriter()));

        Assert.Contains("id: concepts.lacing", output.ToString(), StringComparison.Ordinal);
    }

    /// <summary>
    /// <b>A topic that is not there exits 1 and suggests.</b> Printing nothing and succeeding is
    /// the one outcome a person cannot act on.
    /// </summary>
    [Fact]
    public void AMissingTopicExitsOneAndSuggests()
    {
        StringWriter error = new();
        StringWriter output = new();

        Assert.Equal(1, Program.Docs(["--topic", "nodes.Point.FromCoordinates"], output, error));

        string said = error.ToString();

        Assert.Contains("no help topic 'nodes.Point.FromCoordinates'", said, StringComparison.Ordinal);
        Assert.Contains("nodes.Spark.Nodes.Core/Point.FromCoordinates", said, StringComparison.Ordinal);
        Assert.Equal(string.Empty, output.ToString());
    }

    /// <summary>
    /// An id that matches nothing at all says how to find out what there is, rather than offering
    /// an empty list of suggestions.
    /// </summary>
    [Fact]
    public void AnIdMatchingNothingSaysHowToList()
    {
        StringWriter error = new();

        Assert.Equal(1, Program.Docs(["--topic", "zzzqqq"], new StringWriter(), error));

        Assert.Contains("spark docs", error.ToString(), StringComparison.Ordinal);
    }

    /// <summary>
    /// <c>--out</c> writes every topic as Markdown, in a tree that mirrors the topic ids.
    /// </summary>
    [Fact]
    public void OutWritesEveryTopicAsAFile()
    {
        StringWriter output = new();

        Assert.Equal(0, Program.Docs(["--out", _root], output, new StringWriter()));

        string[] written = Directory.GetFiles(_root, "*.md", SearchOption.AllDirectories);

        Assert.NotEmpty(written);
        Assert.Contains("wrote ", output.ToString(), StringComparison.Ordinal);

        Assert.True(
            File.Exists(Path.Combine(_root, "concepts", "lacing.md")),
            "the topic tree does not mirror the topic ids");

        // kind / package / node, which is what the id means - not one directory per dot, which
        // shreds the package into three and invents a node family out of `Point.FromCoordinates`.
        Assert.True(
            File.Exists(Path.Combine(
                _root, "nodes", "Spark.Nodes.Core", "Point.FromCoordinates.md")),
            "a node page did not land under its key");

        Assert.True(
            File.Exists(Path.Combine(_root, "nodes", "index.md")),
            "the node index did not land beside the pages it indexes");
    }

    /// <summary>
    /// <b>Every file written parses back to the topic it came from.</b> Writing a tree of Markdown
    /// nothing can read would be a silent, total failure — the files would exist and look right.
    /// </summary>
    [Fact]
    public void EveryFileWrittenParsesBack()
    {
        Assert.Equal(0, Program.Docs(["--out", _root], new StringWriter(), new StringWriter()));

        foreach (string file in Directory.GetFiles(_root, "*.md", SearchOption.AllDirectories))
        {
            HelpDocument parsed = HelpMarkdown.Parse(File.ReadAllText(file), "unused");

            Assert.NotEqual("unused", parsed.Id);
            Assert.NotEmpty(parsed.Blocks);
        }
    }

    /// <summary>
    /// Writing twice produces identical bytes, so regenerating a published tree gives an empty diff
    /// rather than churn.
    /// </summary>
    [Fact]
    public void WritingTwiceProducesTheSameBytes()
    {
        string first = Path.Combine(_root, "first");
        string second = Path.Combine(_root, "second");

        Assert.Equal(0, Program.Docs(["--out", first], new StringWriter(), new StringWriter()));
        Assert.Equal(0, Program.Docs(["--out", second], new StringWriter(), new StringWriter()));

        string[] left = [.. Directory.GetFiles(first, "*.md", SearchOption.AllDirectories)
            .Select(path => Path.GetRelativePath(first, path))
            .OrderBy(path => path, StringComparer.Ordinal)];

        string[] right = [.. Directory.GetFiles(second, "*.md", SearchOption.AllDirectories)
            .Select(path => Path.GetRelativePath(second, path))
            .OrderBy(path => path, StringComparer.Ordinal)];

        Assert.Equal(left, right);

        foreach (string relative in left)
        {
            Assert.Equal(
                File.ReadAllText(Path.Combine(first, relative)),
                File.ReadAllText(Path.Combine(second, relative)));
        }
    }

    /// <summary>
    /// <b>Nothing written carries a carriage return.</b> A tree generated on Windows and one
    /// generated on Linux have to be the same bytes, or publishing from either shows every file as
    /// changed.
    /// </summary>
    [Fact]
    public void NothingWrittenCarriesACarriageReturn()
    {
        Assert.Equal(0, Program.Docs(["--out", _root], new StringWriter(), new StringWriter()));

        foreach (string file in Directory.GetFiles(_root, "*.md", SearchOption.AllDirectories))
        {
            Assert.DoesNotContain('\r', File.ReadAllText(file));
        }
    }

    /// <summary>The two modes are exclusive, and saying so beats guessing which was meant.</summary>
    [Fact]
    public void TopicAndOutTogetherAreRefused()
    {
        StringWriter error = new();

        Assert.Equal(1, Program.Docs(
            ["--topic", "concepts.lacing", "--out", _root], new StringWriter(), error));

        Assert.Contains("not both", error.ToString(), StringComparison.Ordinal);
    }

    /// <summary>An option this verb does not have is named rather than ignored.</summary>
    [Fact]
    public void AnUnknownOptionIsNamed()
    {
        StringWriter error = new();

        Assert.Equal(1, Program.Docs(["--all"], new StringWriter(), error));

        Assert.Contains("unrecognised option '--all'", error.ToString(), StringComparison.Ordinal);
    }
}
