<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Spark.Desktop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spark.UI\Spark.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>
</Project>
