using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Media.Imaging;
using Avalonia.Platform;
using Avalonia.Platform.Storage;
using Avalonia.Threading;
using Spark.UI.Controls;
using Spark.UI.Graph;
using Spark.UI.ViewModels;

namespace Spark.UI.Views;

/// <summary>
/// The application's main window: a toolbar, a library pane, the node canvas, the 3D viewport, a
/// properties pane and a status bar.
/// </summary>
/// <remarks>
/// The window also hosts the canvas benchmark, because the measurement ADR-0013 rests on has to be
/// taken through the real compositor rather than through a synthetic harness. A harness that calls
/// <c>Render</c> in a loop measures our own code and nothing else, and our own code is not the part
/// anybody doubted.
/// </remarks>
public sealed partial class MainWindow : Window
{
    private readonly Stopwatch _wallClock = new();
    private int _benchmarkFrames;
    private int _framesRun;
    private bool _benchmarkStarted;
    private int _peakVisibleNodes;
    private Canvas.CanvasBounds _benchmarkBounds;

    /// <summary>Creates the window.</summary>
    public MainWindow()
    {
        // InitializeComponent is generated by Avalonia's name generator: it loads the XAML and
        // assigns the x:Name fields. Declaring one by hand here shadows it, the fields stay null,
        // and the first line below throws — which is exactly what happened the first time.
        InitializeComponent();

        Canvas.ShowFrameStatistics = true;

        // The canvas reports gestures; the view model runs the graph. A view that started an
        // evaluation would be doing it on the thread it draws on (ADR-0005).
        Canvas.GraphChanged += OnCanvasGraphChanged;
        Canvas.SelectionChanged += OnCanvasSelectionChanged;

        // The library pane cannot see the canvas, and should not: where a node lands depends on
        // what is already on the surface. It asks, and the window is what knows both halves.
        LibraryPane.PlaceRequested += (_, _) => PlaceSelectedLibraryEntry();

        DataContextChanged += OnDataContextChanged;
        Opened += OnOpened;
    }

    private MainWindowViewModel? Model => DataContext as MainWindowViewModel;

    /// <summary>
    /// The canvas inside <c>CanvasPane</c>. The window drives the surface — binding the graph,
    /// framing it, running the benchmark over it — while the pane owns the gestures that happen
    /// on it. Named so that the two are not the same thing by accident.
    /// </summary>
    private GraphCanvas Canvas => CanvasPane.Canvas;

    /// <summary>The viewport inside <c>ViewportPane</c>, for the same reason.</summary>
    private ViewportControl Viewport => ViewportPane.Viewport;

    private void OnDataContextChanged(object? sender, EventArgs e)
    {
        if (Model is not { } model)
        {
            return;
        }

        Viewport.Scene = model.Scene;
        model.GraphReplaced += (_, _) => BindGraph(frame: true);

        // Undo rebinds without reframing. A canvas that re-zooms on every Ctrl+Z makes a step
        // backwards feel like a document load, and the user loses their place in their own graph.
        model.DocumentRestored += (_, _) => BindGraph(frame: false);
        model.EvaluationCompleted += OnEvaluationCompleted;
        BindGraph(frame: true);
    }

    private void BindGraph(bool frame)
    {
        if (Model is not { } model)
        {
            return;
        }

        Canvas.Graph = model.Graph;

        if (frame)
        {
            Canvas.ZoomToFit();
        }

        model.ShowSelection(Canvas.Selection);
    }

    private void OnEvaluationCompleted(object? sender, EventArgs e)
    {
        Canvas.InvalidateVisual();
        Viewport.InvalidateGeometry();
        UpdateStatus();
    }

    /// <summary>
    /// Records what the canvas did on the undo stack, and runs the graph when the edit could have
    /// changed an answer.
    /// </summary>
    /// <remarks>
    /// Moving a node reaches here with <c>AffectsEvaluation</c> false. It is a document change and
    /// it goes on the stack; it is not a reason to evaluate, because a position is not in a node's
    /// provenance and cannot change what the node produces.
    /// </remarks>
    /// <param name="sender">The canvas.</param>
    /// <param name="e">What the gesture did.</param>
    private void OnCanvasGraphChanged(object? sender, GraphEditedEventArgs e)
    {
        if (Model is not { } model)
        {
            return;
        }

        model.RecordEdit(e.Label);

        if (e.AffectsEvaluation)
        {
            _ = model.EvaluateAsync();
        }
    }

    private void OnCanvasSelectionChanged(object? sender, EventArgs e) =>
        Model?.ShowSelection(Canvas.Selection);

    private void OnRun(object? sender, RoutedEventArgs e)
    {
        if (Model is { } model)
        {
            _ = model.EvaluateAsync();
        }
    }

    /// <summary>
    /// The file type the open and save dialogs offer. Declared once because two dialogs disagreeing
    /// about an extension is exactly the kind of thing nobody notices until a user cannot find their
    /// own graph.
    /// </summary>
    private static FilePickerFileType GraphFileType => new("Spark graph")
    {
        Patterns = ["*.spark"],
    };

    private async void OnOpenGraph(object? sender, RoutedEventArgs e)
    {
        if (Model is not { } model)
        {
            return;
        }

        IReadOnlyList<IStorageFile> chosen = await StorageProvider.OpenFilePickerAsync(
            new FilePickerOpenOptions
            {
                Title = "Open graph",
                AllowMultiple = false,
                FileTypeFilter = [GraphFileType],
            }).ConfigureAwait(true);

        if (chosen.Count == 0)
        {
            return;
        }

        try
        {
            await using Stream stream = await chosen[0].OpenReadAsync().ConfigureAwait(true);
            using StreamReader reader = new(stream);
            string text = await reader.ReadToEndAsync().ConfigureAwait(true);

            // The view model reports its own refusals into the diagnostics pane. A refused file is
            // a diagnostic like any other, and the view is not allowed to name the engine type that
            // would carry it (E8-T11).
            if (model.TryOpenDocument(text))
            {
                _documentPath = chosen[0].TryGetLocalPath();
                Canvas.ZoomToFit();
                Viewport.ZoomToFit();
            }
        }
        catch (IOException error)
        {
            model.ReportFailure($"That file could not be read: {error.Message}");
        }

        UpdateStatus();
    }

    private async void OnSaveGraph(object? sender, RoutedEventArgs e)
    {
        if (Model is not { } model)
        {
            return;
        }

        if (model.TrySaveDocument() is not { } text)
        {
            return;
        }

        IStorageFile? target = await StorageProvider.SaveFilePickerAsync(
            new FilePickerSaveOptions
            {
                Title = "Save graph",
                DefaultExtension = "spark",
                SuggestedFileName = Path.GetFileName(_documentPath) ?? "graph.spark",
                FileTypeChoices = [GraphFileType],
            }).ConfigureAwait(true);

        if (target is null)
        {
            return;
        }

        try
        {
            await using Stream stream = await target.OpenWriteAsync().ConfigureAwait(true);
            await using StreamWriter writer = new(stream);
            await writer.WriteAsync(text).ConfigureAwait(true);
            _documentPath = target.TryGetLocalPath();
        }
        catch (IOException error)
        {
            model.ReportFailure($"That file could not be written: {error.Message}");
        }

        UpdateStatus();
    }

    private void PlaceSelectedLibraryEntry()
    {
        if (Model is not { } model)
        {
            return;
        }

        Canvas.SuggestPlacement(model.PlacementOrdinal, out double x, out double y);

        int slot = model.PlaceSelectedLibraryEntry(x, y);
        if (slot < 0)
        {
            return;
        }

        Canvas.RefreshStructure();
        Canvas.SelectOnly(slot);
        Canvas.Focus();
        _ = model.EvaluateAsync();
    }

    private string? _documentPath;

    /// <summary>Command-line options, chiefly the benchmark switches.</summary>
    public StartupOptions Options { get; set; } = StartupOptions.Default;

    private void OnOpened(object? sender, EventArgs e)
    {
        if (Options.SyntheticNodeCount > 0)
        {
            LoadSynthetic(Options.SyntheticNodeCount);
        }
        else
        {
            // A file named on the command line was already opened by the view model's
            // constructor, so there is exactly one graph adoption and one evaluation.
            Canvas.ZoomToFit();
        }

        UpdateStatus();

        if (Options.IsBenchmark)
        {
            StartBenchmark(Options.BenchmarkFrames);
            return;
        }

        if (Options.IsScreenshot)
        {
            // The demo graph is evaluated on construction; the capture waits for that run to have
            // landed, because a screenshot taken before the first evaluation shows an empty
            // viewport and proves nothing at all.
            _ = CaptureWhenReadyAsync(Options.ScreenshotPrefix!);
            return;
        }

        Viewport.ZoomToFit();
    }

    private async Task CaptureWhenReadyAsync(string prefix)
    {
        if (Model is { } model)
        {
            await model.EvaluateAsync().ConfigureAwait(true);
        }

        Canvas.ZoomToFit();
        Viewport.ZoomToFit();
        StartCapture(prefix);
    }

    /// <summary>
    /// Writes a picture of the shell and a picture of the viewport, then exits.
    /// </summary>
    /// <param name="prefix">The file path prefix the two images are written under.</param>
    /// <remarks>
    /// The two images are taken by different means on purpose. The shell is rendered through
    /// Avalonia's own render-target path, which captures the immediate-mode canvas exactly as the
    /// compositor sees it. The viewport is a <c>glReadPixels</c> read-back off the GPU, because the
    /// GL surface is composited separately and does not appear in a visual-tree render — and
    /// because a read-back is the only way to answer "is it drawing anything?" on a machine whose
    /// session is locked, which is also the situation in CI.
    /// </remarks>
    private void StartCapture(string prefix)
    {
        if (Options.BenchmarkZoom > 0)
        {
            // Centre on the graph after zooming. Setting the zoom alone scales about the world
            // origin, which at any zoom above the fit takes every node off screen — and a
            // screenshot switch that reliably photographs empty canvas is worse than none.
            Canvas.Transform.Zoom = Options.BenchmarkZoom;
            Canvas.CentreOn(Canvas.Graph.ComputeBounds());
        }

        Viewport.RequestCapture();

        // Two dispatcher turns at background priority: one for the GL frame that services the
        // capture request, one for it to have completed before the read.
        DispatcherTimer.RunOnce(
            () => DispatcherTimer.RunOnce(() => WriteCaptures(prefix), TimeSpan.FromMilliseconds(400)),
            TimeSpan.FromMilliseconds(600));
    }

    private void WriteCaptures(string prefix)
    {
        UpdateStatus();

        int width = Math.Max(1, (int)Bounds.Width);
        int height = Math.Max(1, (int)Bounds.Height);

        using (RenderTargetBitmap shell = new(new PixelSize(width, height), new Vector(96, 96)))
        {
            shell.Render(this);
            shell.Save(prefix + "-shell.png", PngBitmapEncoderOptions.Default);
        }

        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture, $"wrote {prefix}-shell.png ({width}x{height})"));

        byte[]? pixels = Viewport.TakeCapture(out int glWidth, out int glHeight);
        if (pixels is null)
        {
            Console.WriteLine("no viewport read-back: the GL context produced no frame.");
            Close();
            return;
        }

        using (WriteableBitmap viewport = new(
            new PixelSize(glWidth, glHeight), new Vector(96, 96), PixelFormat.Rgba8888, AlphaFormat.Opaque))
        {
            using (ILockedFramebuffer buffer = viewport.Lock())
            {
                // glReadPixels hands back the bottom row first; every image format Spark writes
                // wants the top row first.
                for (int row = 0; row < glHeight; row++)
                {
                    int source = (glHeight - 1 - row) * glWidth * 4;
                    Marshal.Copy(pixels, source, buffer.Address + (row * buffer.RowBytes), glWidth * 4);
                }
            }

            viewport.Save(prefix + "-viewport.png", PngBitmapEncoderOptions.Default);
        }

        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"wrote {prefix}-viewport.png ({glWidth}x{glHeight}); {DescribePixels(pixels)}"));
        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture, $"viewport status: {Viewport.Status}"));

        Close();
    }

    /// <summary>
    /// Summarises a read-back so the console alone can distinguish "drew a scene" from "cleared to
    /// one colour" and from "drew nothing at all".
    /// </summary>
    /// <param name="rgba">The read-back pixels.</param>
    /// <returns>A one-line description.</returns>
    private static string DescribePixels(byte[] rgba)
    {
        System.Collections.Generic.HashSet<int> distinct = [];
        long luminanceTotal = 0;
        int samples = 0;

        for (int i = 0; i + 3 < rgba.Length; i += 4)
        {
            distinct.Add((rgba[i] << 16) | (rgba[i + 1] << 8) | rgba[i + 2]);
            luminanceTotal += (rgba[i] * 2) + (rgba[i + 1] * 5) + rgba[i + 2];
            samples++;

            if (distinct.Count > 20000)
            {
                break;
            }
        }

        double mean = samples == 0 ? 0 : luminanceTotal / (double)samples / 8.0;
        return string.Create(
            CultureInfo.InvariantCulture,
            $"{distinct.Count} distinct colours, mean luminance {mean:F1}/255");
    }

    private void OnZoomToFit(object? sender, RoutedEventArgs e)
    {
        Canvas.ZoomToFit();
        UpdateStatus();
    }

    private void OnFrameViewport(object? sender, RoutedEventArgs e) => Viewport.ZoomToFit();

    private void OnLoadSynthetic(object? sender, RoutedEventArgs e) => LoadSynthetic(2000);

    private void OnLoadDemo(object? sender, RoutedEventArgs e) => Model?.LoadDemo();

    private void OnLoadCurves(object? sender, RoutedEventArgs e) => Model?.LoadCurves();

    private void LoadSynthetic(int nodeCount) => Model?.LoadSynthetic(nodeCount);

    private void UpdateStatus()
    {
        if (Model is not { } model)
        {
            return;
        }

        model.ViewportStatusText = Viewport.Status ?? "Waiting for the OpenGL context.";
    }

    /// <summary>
    /// Drives a fixed pan-and-zoom cycle for a set number of compositor frames, then prints the
    /// distribution and exits.
    /// </summary>
    /// <param name="frames">How many frames to run, including a warm-up.</param>
    /// <remarks>
    /// The cycle is deterministic — a sinusoidal pan across roughly a screen width and a zoom
    /// sweep between 25% and 110% — so two runs are comparable and a regression is a number rather
    /// than an impression. The first sixth of the run is discarded: it contains JIT, the first
    /// text layout of every distinct node title and the first spatial-index build, none of which
    /// recur.
    /// </remarks>
    private void StartBenchmark(int frames)
    {
        if (_benchmarkStarted)
        {
            return;
        }

        _benchmarkStarted = true;
        _benchmarkFrames = Math.Max(60, frames);
        _framesRun = 0;
        _peakVisibleNodes = 0;

        // Give the canvas the whole window. Measuring it inside a third of the centre column
        // would produce a flattering number for the wrong reason: a smaller viewport culls more,
        // and the claim being tested is about how many nodes can be ON SCREEN at 60 fps.
        LibraryPane.IsVisible = false;
        InspectorPane.IsVisible = false;
        ViewportPane.IsVisible = false;
        ShellColumns.ColumnDefinitions = new ColumnDefinitions("0,0,*,0,0");
        CentreRows.RowDefinitions = new RowDefinitions("*,0,0");

        _benchmarkBounds = Canvas.Graph.ComputeBounds();
        _wallClock.Restart();
        RequestAnimationFrame(OnBenchmarkFrame);
    }

    private void OnBenchmarkFrame(TimeSpan _)
    {
        _framesRun++;

        // A deterministic sweep: three zoom cycles between 30% and 90%, and a centre that travels
        // twice around the graph, so every frame has the canvas full of nodes and the run covers
        // both sides of every level-of-detail threshold. Two runs are therefore comparable and a
        // regression is a number rather than an impression.
        double phase = _framesRun / (double)_benchmarkFrames;
        double zoom = Options.BenchmarkZoom > 0
            ? Options.BenchmarkZoom
            : 0.30 + (0.60 * (0.5 - (0.5 * Math.Cos(phase * Math.Tau * 3))));
        double centreX = _benchmarkBounds.MinX + (_benchmarkBounds.Width * (0.5 + (0.35 * Math.Sin(phase * Math.Tau * 2))));
        double centreY = _benchmarkBounds.MinY + (_benchmarkBounds.Height * (0.5 + (0.35 * Math.Cos(phase * Math.Tau * 2))));

        Canvas.Transform.Zoom = zoom;
        Canvas.Transform.OffsetX = centreX - (Canvas.Bounds.Width / (2 * zoom));
        Canvas.Transform.OffsetY = centreY - (Canvas.Bounds.Height / (2 * zoom));
        Canvas.InvalidateVisual();

        int warmUp = _benchmarkFrames / 6;
        if (_framesRun == warmUp)
        {
            // Discard the warm-up: it contains JIT, the first text layout of every distinct node
            // title and the first spatial-index build, none of which recur.
            Canvas.Frames.Reset();
            _peakVisibleNodes = 0;
            _wallClock.Restart();
        }

        _peakVisibleNodes = Math.Max(_peakVisibleNodes, Canvas.LastVisibleNodeCount);

        if (_framesRun < _benchmarkFrames)
        {
            RequestAnimationFrame(OnBenchmarkFrame);
            return;
        }

        int measured = _benchmarkFrames - warmUp;
        double wallMilliseconds = _wallClock.Elapsed.TotalMilliseconds;

        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"canvas-benchmark nodes={Canvas.Graph.Nodes.Count} wires={Canvas.Graph.Wires.Count} " +
            $"frames={measured} surface={Canvas.Bounds.Width:F0}x{Canvas.Bounds.Height:F0}"));
        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"  render pass: {Canvas.Frames.Summary()}"));
        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"  wall clock:  {wallMilliseconds / measured:F2} ms per frame, " +
            $"{measured / (wallMilliseconds / 1000.0):F0} fps"));
        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"  cull:        peak {_peakVisibleNodes} nodes on screen; last frame " +
            $"{Canvas.LastVisibleNodeCount} visible of {Canvas.LastConsideredNodeCount} considered " +
            $"at zoom {Canvas.Transform.Zoom * 100:F0}%"));
        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"  viewport:    {Viewport.Status ?? "no GL callback ran"}"));

        Close();
    }

}
