using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Media.Imaging;
using Avalonia.Platform;
using Avalonia.Platform.Storage;
using Avalonia.Threading;
using Spark.UI.Canvas;
using Spark.UI.Controls;
using Spark.UI.Graph;
using Spark.UI.Shell;
using Spark.UI.ViewModels;
using Spark.UI.Views;
using Spark.UI.Views.Panes;

namespace Spark.UI.Views;

/// <summary>
/// The application's main window: a toolbar, a library pane, the node canvas, the 3D viewport, a
/// properties pane and a status bar.
/// </summary>
/// <remarks>
/// The window also hosts the canvas benchmark, because the measurement ADR-0013 rests on has to be
/// taken through the real compositor rather than through a synthetic harness. A harness that calls
/// <c>Render</c> in a loop measures our own code and nothing else, and our own code is not the part
/// anybody doubted.
/// </remarks>
public sealed partial class MainWindow : Window
{
    private readonly SparkDockFactory _dock = new();
    private readonly LibraryPane _libraryPane = new();
    private readonly CanvasPane _canvasPane = new();
    private readonly ViewportPane _viewportPane = new();
    private readonly InspectorPane _inspectorPane = new();
    private readonly Stopwatch _wallClock = new();
    private int _benchmarkFrames;
    private int _framesRun;
    private bool _benchmarkStarted;
    private int _peakVisibleNodes;
    private Canvas.CanvasBounds _benchmarkBounds;

    /// <summary>Creates the window.</summary>
    public MainWindow()
    {
        // InitializeComponent is generated by Avalonia's name generator: it loads the XAML and
        // assigns the x:Name fields. Declaring one by hand here shadows it, the fields stay null,
        // and the first line below throws — which is exactly what happened the first time.
        InitializeComponent();

        // The panes are constructed here rather than declared in the XAML because a Tool's
        // Content is a template (N34): declaring them inline would build them into a namescope
        // this window cannot reach, and everything below reaches them.
        Shell.Factory = _dock;
        Shell.Layout = _dock.Build(new Dictionary<WorkspacePane, object?>
        {
            [WorkspacePane.Library] = _libraryPane,
            [WorkspacePane.Canvas] = _canvasPane,
            [WorkspacePane.Viewport] = _viewportPane,
            [WorkspacePane.Inspector] = _inspectorPane,
        });

        Canvas.ShowFrameStatistics = true;

        // The canvas reports gestures; the view model runs the graph. A view that started an
        // evaluation would be doing it on the thread it draws on (ADR-0005).
        Canvas.GraphChanged += OnCanvasGraphChanged;
        Canvas.SelectionChanged += OnCanvasSelectionChanged;

        // Nothing is selected yet, so Align starts disabled. Left to the first SelectionChanged
        // it would start enabled over an empty selection and do nothing when pressed.
        UpdateAlignAvailability();

        // The library pane cannot see the canvas, and should not: where a node lands depends on
        // what is already on the surface. It asks, and the window is what knows both halves.
        _libraryPane.PlaceRequested += (_, _) => PlaceSelectedLibraryEntry();

        // The pane owns the text box; the canvas owns the pixels; the shell owns the undo stack.
        // The pane tells the window the text changed, and the window tells the other two.
        _inspectorPane.NoteEdited += (_, _) => Canvas.NoteTextEdited();
        _inspectorPane.GroupRenamed += (_, _) => Canvas.GroupTitleEdited();

        // A code block's ports change when its script does, so the canvas has to rebuild its
        // structure rather than merely repaint - which is the one way editing a script differs
        // from editing a note.
        _inspectorPane.ScriptEdited += (_, _) =>
        {
            Canvas.RefreshStructure();
            Canvas.InvalidateVisual();
            _ = Model?.EvaluateAsync();
        };

        DataContextChanged += OnDataContextChanged;
        Opened += OnOpened;
    }

    private HelpWindow? _help;
    private AboutWindow? _about;
    private PackageWindow? _packages;

    private MainWindowViewModel? Model => DataContext as MainWindowViewModel;

    /// <summary>
    /// The canvas inside <c>CanvasPane</c>. The window drives the surface — binding the graph,
    /// framing it, running the benchmark over it — while the pane owns the gestures that happen
    /// on it. Named so that the two are not the same thing by accident.
    /// </summary>
    private GraphCanvas Canvas => _canvasPane.Canvas;

    /// <summary>The viewport inside <c>ViewportPane</c>, for the same reason.</summary>
    private ViewportControl Viewport => _viewportPane.Viewport;

    private void OnDataContextChanged(object? sender, EventArgs e)
    {
        if (Model is not { } model)
        {
            return;
        }

        _dock.SetContext(model);

        model.WorkspaceChanged += (_, _) => _dock.Apply(model.Layout);
        _dock.Apply(model.Layout);

        Viewport.Scene = model.Scene;
        model.GraphReplaced += (_, _) => BindGraph(frame: true);

        // Undo rebinds without reframing. A canvas that re-zooms on every Ctrl+Z makes a step
        // backwards feel like a document load, and the user loses their place in their own graph.
        model.DocumentRestored += (_, _) => BindGraph(frame: false);
        model.EvaluationCompleted += OnEvaluationCompleted;
        BindGraph(frame: true);
    }

    private void BindGraph(bool frame)
    {
        if (Model is not { } model)
        {
            return;
        }

        Canvas.Graph = model.Graph;

        if (frame)
        {
            Canvas.ZoomToFit();
        }

        model.ShowSelection(Canvas.Selection);
    }

    private void OnEvaluationCompleted(object? sender, EventArgs e)
    {
        Canvas.InvalidateVisual();
        Viewport.InvalidateGeometry();
        UpdateStatus();
    }

    /// <summary>
    /// Records what the canvas did on the undo stack, and runs the graph when the edit could have
    /// changed an answer.
    /// </summary>
    /// <remarks>
    /// Moving a node reaches here with <c>AffectsEvaluation</c> false. It is a document change and
    /// it goes on the stack; it is not a reason to evaluate, because a position is not in a node's
    /// provenance and cannot change what the node produces.
    /// </remarks>
    /// <param name="sender">The canvas.</param>
    /// <param name="e">What the gesture did.</param>
    private void OnCanvasGraphChanged(object? sender, GraphEditedEventArgs e)
    {
        if (Model is not { } model)
        {
            return;
        }

        model.RecordEdit(e.Label);

        if (e.AffectsEvaluation)
        {
            _ = model.EvaluateAsync();
        }
    }

    private void OnOpenHelp(object? sender, RoutedEventArgs e) => OpenHelp();

    private void OnOpenPackages(object? sender, RoutedEventArgs e) => OpenPackages();
    private void OnDismissMissing(object? sender, RoutedEventArgs e) => MissingBanner.IsVisible = false;

    /// <summary>
    /// Opens the package manager already searching for the package the banner names
    /// (<c>E7-T6</c>).
    /// </summary>
    /// <remarks>
    /// <b>It searches rather than installs, and the row's phrase <i>one-click install</i> is still
    /// honoured by that.</b> Installing straight from a banner would skip the disclosure, which is
    /// the one screen where a user decides whether to run somebody else's code. One click gets them
    /// to the package with the answer in front of them; the click after it is the agreement.
    /// </remarks>
    private void OnInstallMissing(object? sender, RoutedEventArgs e)
    {
        if (Model is not { } model || model.MissingPackages() is not { Count: > 0 } missing)
        {
            return;
        }

        if (model.Packages() is { } packages)
        {
            packages.Query = missing[0];
        }

        OpenPackages();

        if (_packages is not null)
        {
            _ = _packages.Model.SearchAsync();
        }
    }

    /// <summary>
    /// Shows or hides the missing-package banner for whatever graph is now on the canvas.
    /// </summary>
    /// <remarks>
    /// Recomputed rather than remembered, so the banner goes away by itself once the package is
    /// installed and the nodes resolve. There is nothing to invalidate and nothing to get wrong.
    /// </remarks>
    private void UpdateMissingBanner()
    {
        if (Model is not { } model)
        {
            return;
        }

        IReadOnlyList<string> missing = model.MissingPackages();

        MissingBanner.IsVisible = missing.Count > 0;

        if (missing.Count == 0)
        {
            return;
        }

        MissingInstallButton.Content = "Find " + missing[0];

        MissingBannerText.Text = missing.Count == 1
            ? $"This graph uses nodes from '{missing[0]}', which is not installed. "
                + "Those nodes are kept exactly as they were and the file will save unchanged."
            : $"This graph uses nodes from {missing.Count} packages that are not installed: "
                + string.Join(", ", missing)
                + ". Those nodes are kept exactly as they were and the file will save unchanged.";
    }


    /// <summary>
    /// Runs the startup feed search and, when one was named, prepares that package so its
    /// disclosure is on screen. <b>Nothing is installed</b>: preparing is the step that asks.
    /// </summary>
    private static async System.Threading.Tasks.Task SearchThenPrepareAsync(
        PackageWindow window, string? prepare)
    {
        await window.Model.SearchAsync().ConfigureAwait(true);

        if (string.IsNullOrWhiteSpace(prepare))
        {
            return;
        }

        foreach (Spark.UI.ViewModels.PackageRow row in window.Model.Results)
        {
            if (string.Equals(row.Id, prepare, StringComparison.OrdinalIgnoreCase))
            {
                await window.Model.PrepareAsync(row).ConfigureAwait(true);
                return;
            }
        }
    }

    /// <summary>
    /// Opens the package manager (<c>E7-T10</c>).
    /// </summary>
    /// <remarks>
    /// <b>One window, reused</b>, for the reason help is: a second copy would let a user prepare
    /// an install in one and answer a stale disclosure in the other. The window discards anything
    /// prepared and unanswered when it closes, so a download never outlives the question it was
    /// fetched to answer.
    /// </remarks>
    private void OpenPackages()
    {
        if (Model is not { } model)
        {
            return;
        }

        if (_packages is null || !_packages.IsVisible)
        {
            _packages = new PackageWindow(model.Packages(), model.LocalReferences());
            _packages.Closed += (_, _) => _packages = null;
            _packages.Show(this);
        }
        else
        {
            _packages.Activate();
        }
    }

    /// <summary>
    /// Opens the About box.
    /// </summary>
    /// <remarks>
    /// <b>A licence obligation rather than an ornament</b> (`E12-T18`, `E13-T16`, `R21`): the Open
    /// CASCADE exception requires prominent notice that the work uses facilities provided by the
    /// Open CASCADE Technology software, and About is where a user with only an installer looks.
    /// The text itself is in <c>ProductNotice</c>, shared with <c>spark --version</c>, because two
    /// copies of a licence statement is one copy that eventually stops matching the build.
    /// </remarks>
    private void OnOpenAbout(object? sender, RoutedEventArgs e)
    {
        // Asked through the contract rather than by type, because Spark.UI deliberately does not
        // reference the provider - the entry point installs it, and the shell only ever sees an
        // IBrepKernel. Passing null when none is loaded is what makes the About box say so rather
        // than print the no-op stand-in's name as though it were a modelling kernel.
        Spark.Api.IBrepKernel kernel = Spark.Api.BrepKernel.Current;
        string? description = kernel is Spark.Api.UnavailableBrepKernel ? null : kernel.Description;

        AboutWindow about = new(
            typeof(MainWindow).Assembly.GetName().Version?.ToString(), description);

        about.ShowDialog(this);
    }

    /// <inheritdoc/>
    protected override void OnKeyDown(KeyEventArgs e)
    {
        base.OnKeyDown(e);

        if (e.Key == Key.F1)
        {
            OpenHelp();
            e.Handled = true;
        }
    }

    /// <summary>
    /// Opens the help window on the selected node's topic, or on the node index when nothing is
    /// selected.
    /// </summary>
    /// <remarks>
    /// <b>F1 is context-sensitive because that is the only kind of F1 anybody presses.</b> A help
    /// key that always opens the same front page is a help key nobody uses twice: the moment worth
    /// serving is a user looking at a node they do not understand, and the answer is that node's
    /// page rather than a table of contents.
    /// <para>
    /// One window, reused. Opening a second on every press would leave a user with a stack of
    /// identical windows and no clue which one they were reading.
    /// </para>
    /// </remarks>
    private void OpenHelp()
    {
        if (Model is not { } model)
        {
            return;
        }

        if (_help is null || !_help.IsVisible)
        {
            _help = new HelpWindow(model.Help());
            _help.Closed += (_, _) => _help = null;
            _help.Show(this);
        }
        else
        {
            _help.Activate();
        }

        _help.NavigateToNode(SelectedNodeKey());
    }

    /// <summary>The key of the single selected node, or null when the selection is not one node.</summary>
    private string? SelectedNodeKey()
    {
        if (Model is not { } model || Canvas.Selection.Count != 1)
        {
            return null;
        }

        foreach (int slot in Canvas.Selection)
        {
            return model.NodeKeyAt(slot);
        }

        return null;
    }

    private void OnCanvasSelectionChanged(object? sender, EventArgs e)
    {
        // The annotations first, because selecting either clears the node selection: asking the
        // other way round would show "Nothing selected" over something that plainly is.
        if (Canvas.SelectedNote is { } note)
        {
            Model?.ShowNote(note);
        }
        else if (Canvas.SelectedGroup is { } group)
        {
            Model?.ShowGroup(group);
        }
        else
        {
            Model?.ShowSelection(Canvas.Selection);
        }

        // Selection has two consequences, and the viewport is the second: the geometry a selected
        // node produced is outlined in the accent colour. It falls out of node-keyed identity with
        // no extra bookkeeping (E9-T9) and costs no GPU upload, because appearance is a uniform.
        if (Model?.ShowSelectionInViewport(Canvas.Selection) == true)
        {
            Viewport.InvalidateGeometry();
        }

        UpdateAlignAvailability();
    }

    /// <summary>Places a code block where a new node would go.</summary>
    private void OnAddCodeBlock(object? sender, RoutedEventArgs e)
    {
        if (Model is not { } model)
        {
            return;
        }

        Canvas.SuggestPlacement(model.PlacementOrdinal, out double x, out double y);

        int slot = model.PlaceCodeBlock(x, y);
        if (slot < 0)
        {
            return;
        }

        Canvas.RefreshStructure();
        Canvas.SelectOnly(slot);
        Canvas.Focus();
        _ = model.EvaluateAsync();
    }

    /// <summary>Frames the selected nodes in a group.</summary>
    private void OnGroupSelection(object? sender, RoutedEventArgs e)
    {
        Canvas.GroupSelection();
        UpdateStatus();
    }

    /// <summary>
    /// Replaces the selected nodes with a single custom node (<c>E7-T12</c>).
    /// </summary>
    /// <remarks>
    /// <b>The refusal is reported in the status bar rather than swallowed.</b> A selection nothing
    /// reads cannot become a node, and a button that appears to do nothing is worse than one that
    /// says why.
    /// </remarks>
    private void OnCollapseSelection(object? sender, RoutedEventArgs e)
    {
        if (Model is not { } model)
        {
            return;
        }

        int? slot = model.CollapseSelection(Canvas.Selection, out string? reason);

        if (slot is null)
        {
            model.StatusText = reason ?? "The selection cannot be collapsed.";
            return;
        }

        Canvas.CollapsedInto(slot.Value);
        UpdateStatus();
    }

    /// <summary>Puts a new note where a new node would go, and puts the caret in it.</summary>
    private void OnAddNote(object? sender, RoutedEventArgs e)
    {
        Canvas.SuggestPlacement(Model?.PlacementOrdinal ?? 0, out double x, out double y);
        Canvas.AddNote(x, y);
        UpdateStatus();
    }

    /// <summary>
    /// Enables the align menu, and its two distribute items, for the selection there actually is.
    /// </summary>
    /// <remarks>
    /// Done here rather than by binding because the selection lives on the canvas, not on the view
    /// model: it is a canvas gesture's state, and lifting it into the document model to make a
    /// binding possible would be the tail wagging the dog. The window already knows both halves,
    /// which is the same argument that put node placement here.
    /// </remarks>
    private void UpdateAlignAvailability()
    {
        int selected = Canvas.Selection.Count;

        AlignButton.IsEnabled = selected >= CanvasAlignment.MinimumToAlign;
        GroupButton.IsEnabled = Canvas.CanGroupSelection();
        CollapseButton.IsEnabled = Canvas.CanCollapseSelection();
        DistributeHorizontally.IsEnabled = selected >= CanvasAlignment.MinimumToDistribute;
        DistributeVertically.IsEnabled = selected >= CanvasAlignment.MinimumToDistribute;
    }

    /// <summary>
    /// Applies the alignment the clicked menu item names.
    /// </summary>
    /// <remarks>
    /// The operation travels on the item's <c>Tag</c> as the enum's own name, parsed back here.
    /// Eight nearly identical handlers would be the alternative, and the parse fails loudly at the
    /// first click if a Tag is ever misspelt — which a set of eight handlers would not.
    /// </remarks>
    private void OnAlign(object? sender, RoutedEventArgs e)
    {
        if (sender is not MenuItem { Tag: string name })
        {
            return;
        }

        Canvas.AlignSelection(Enum.Parse<CanvasAlign>(name));
        UpdateStatus();
    }

    private void OnRun(object? sender, RoutedEventArgs e)
    {
        if (Model is { } model)
        {
            _ = model.EvaluateAsync();
        }
    }

    /// <summary>
    /// The file type the open and save dialogs offer. Declared once because two dialogs disagreeing
    /// about an extension is exactly the kind of thing nobody notices until a user cannot find their
    /// own graph.
    /// </summary>
    private static FilePickerFileType GraphFileType => new("Spark graph")
    {
        Patterns = ["*.spark"],
    };

    private async void OnOpenGraph(object? sender, RoutedEventArgs e)
    {
        if (Model is not { } model)
        {
            return;
        }

        IReadOnlyList<IStorageFile> chosen = await StorageProvider.OpenFilePickerAsync(
            new FilePickerOpenOptions
            {
                Title = "Open graph",
                AllowMultiple = false,
                FileTypeFilter = [GraphFileType],
            }).ConfigureAwait(true);

        if (chosen.Count == 0)
        {
            return;
        }

        try
        {
            await using Stream stream = await chosen[0].OpenReadAsync().ConfigureAwait(true);
            using StreamReader reader = new(stream);
            string text = await reader.ReadToEndAsync().ConfigureAwait(true);

            // The view model reports its own refusals into the diagnostics pane. A refused file is
            // a diagnostic like any other, and the view is not allowed to name the engine type that
            // would carry it (E8-T11).
            // The origin goes in with the text, because the trust decision is about *this file
            // saying this* (`E6-T16`) - the content alone would trust every copy of a graph
            // anywhere, which is exactly how a malicious one would travel.
            if (model.TryOpenDocument(text, chosen[0].TryGetLocalPath()))
            {
                _documentPath = chosen[0].TryGetLocalPath();
                Canvas.ZoomToFit();
                Viewport.ZoomToFit();
            }
        }
        catch (IOException error)
        {
            model.ReportFailure($"That file could not be read: {error.Message}");
        }

        UpdateStatus();
        UpdateMissingBanner();
    }

    private async void OnSaveGraph(object? sender, RoutedEventArgs e)
    {
        if (Model is not { } model)
        {
            return;
        }

        if (model.TrySaveDocument() is not { } text)
        {
            return;
        }

        IStorageFile? target = await StorageProvider.SaveFilePickerAsync(
            new FilePickerSaveOptions
            {
                Title = "Save graph",
                DefaultExtension = "spark",
                SuggestedFileName = Path.GetFileName(_documentPath) ?? "graph.spark",
                FileTypeChoices = [GraphFileType],
            }).ConfigureAwait(true);

        if (target is null)
        {
            return;
        }

        try
        {
            await using Stream stream = await target.OpenWriteAsync().ConfigureAwait(true);
            await using StreamWriter writer = new(stream);
            await writer.WriteAsync(text).ConfigureAwait(true);
            _documentPath = target.TryGetLocalPath();
        }
        catch (IOException error)
        {
            model.ReportFailure($"That file could not be written: {error.Message}");
        }

        UpdateStatus();
    }

    private void PlaceSelectedLibraryEntry()
    {
        if (Model is not { } model)
        {
            return;
        }

        Canvas.SuggestPlacement(model.PlacementOrdinal, out double x, out double y);

        int slot = model.PlaceSelectedLibraryEntry(x, y);
        if (slot < 0)
        {
            return;
        }

        Canvas.RefreshStructure();
        Canvas.SelectOnly(slot);
        Canvas.Focus();
        _ = model.EvaluateAsync();
    }

    private string? _documentPath;

    /// <summary>Command-line options, chiefly the benchmark switches.</summary>
    public StartupOptions Options { get; set; } = StartupOptions.Default;

    private void OnOpened(object? sender, EventArgs e)
    {
        // Before anything asks for a frame: the switch has to be in place before the first GL
        // callback, or a context is created and then abandoned.
        Viewport.ForceSoftwareRenderer = Options.ForceSoftwareRenderer;

        if (Options.CollapseFirst > 0)
        {
            for (int slot = 0; slot < Options.CollapseFirst && slot < Canvas.Graph.Nodes.Count; slot++)
            {
                Canvas.SelectAlso(slot);
            }

            OnCollapseSelection(this, new RoutedEventArgs());
        }

        if (Options.OpensHelp)
        {
            OpenHelp();
            _help?.Navigate(Options.HelpTopic);
        }

        if (Options.OpensPackages)
        {
            // The query is put on the model before the window is built, so the search box shows
            // what was searched for. The window reads it once and then leaves it alone, because a
            // box that re-synced would erase whatever the user was halfway through typing.
            if (Model is { } packageModel && !string.IsNullOrWhiteSpace(Options.PackageQuery))
            {
                packageModel.Packages().Query = Options.PackageQuery;
            }

            OpenPackages();

            if (!string.IsNullOrWhiteSpace(Options.PackageQuery) && _packages is not null)
            {
                _ = SearchThenPrepareAsync(_packages, Options.PreparePackage);
            }

            // The tab comes to the front whenever --reference was given at all, so passing it an
            // empty value opens the list without prompting about anything. Choosing is separate.
            if (Options.ReferenceAssembly is not null && _packages is not null)
            {
                _packages.ShowLocalAssemblies();

                if (!string.IsNullOrWhiteSpace(Options.ReferenceAssembly))
                {
                    _packages.Local.Choose(Options.ReferenceAssembly);
                }
            }
        }

        if (Options.OpenAbout)
        {
            _about = new AboutWindow(
                typeof(MainWindow).Assembly.GetName().Version?.ToString(),
                Spark.Api.BrepKernel.Current is Spark.Api.UnavailableBrepKernel
                    ? null
                    : Spark.Api.BrepKernel.Current.Description);

            _about.Show(this);
        }

        if (Options.SyntheticNodeCount > 0)
        {
            LoadSynthetic(Options.SyntheticNodeCount);
        }
        else
        {
            // A file named on the command line was already opened by the view model's
            // constructor, so there is exactly one graph adoption and one evaluation.
            Canvas.ZoomToFit();
        }

        UpdateStatus();
        UpdateMissingBanner();

        if (Options.IsBenchmark)
        {
            StartBenchmark(Options.BenchmarkFrames);
            return;
        }

        if (Options.IsScreenshot)
        {
            // The demo graph is evaluated on construction; the capture waits for that run to have
            // landed, because a screenshot taken before the first evaluation shows an empty
            // viewport and proves nothing at all.
            _ = CaptureWhenReadyAsync(Options.ScreenshotPrefix!);
            return;
        }

        Viewport.ZoomToFit();
    }

    private async Task CaptureWhenReadyAsync(string prefix)
    {
        if (Model is { } model)
        {
            await model.EvaluateAsync().ConfigureAwait(true);
        }


        Canvas.ZoomToFit();
        Viewport.ZoomToFit();
        StartCapture(prefix);
    }

    /// <summary>
    /// Writes a picture of the shell and a picture of the viewport, then exits.
    /// </summary>
    /// <param name="prefix">The file path prefix the two images are written under.</param>
    /// <remarks>
    /// The two images are taken by different means on purpose. The shell is rendered through
    /// Avalonia's own render-target path, which captures the immediate-mode canvas exactly as the
    /// compositor sees it. The viewport is a read-back from whichever backend drew it — a
    /// <c>glReadPixels</c> off the GPU, or the software rasteriser's own framebuffer — because the
    /// GL surface is composited separately and does not appear in a visual-tree render, and
    /// because a read-back is the only way to answer "is it drawing anything?" on a machine whose
    /// session is locked, which is also the situation in CI.
    /// </remarks>
    private void StartCapture(string prefix)
    {
        if (Options.BenchmarkZoom > 0)
        {
            // Centre on the graph after zooming. Setting the zoom alone scales about the world
            // origin, which at any zoom above the fit takes every node off screen — and a
            // screenshot switch that reliably photographs empty canvas is worse than none.
            Canvas.Transform.Zoom = Options.BenchmarkZoom;
            Canvas.CentreOn(Canvas.Graph.ComputeBounds());
        }

        Viewport.RequestCapture();

        // Wait for a frame, not for a clock. Which backend services the capture is not something
        // this caller can predict - OpenGL may come up at once, or never - and the software
        // fallback only commits after the viewport has waited out its patience for a GL callback
        // that is not coming. A fixed delay was tuned to the GL case and silently produced no
        // image at all on a machine where GL never initialises, which is precisely the machine the
        // fallback exists for.
        WaitForCapture(prefix, DateTime.UtcNow + TimeSpan.FromSeconds(6));
    }

    /// <summary>
    /// Polls until a frame has been captured or the deadline passes, then writes the images.
    /// </summary>
    /// <param name="prefix">The file path prefix.</param>
    /// <param name="deadline">When to give up and write whatever there is.</param>
    /// <remarks>
    /// Polling rather than an event, because the two backends signal completion in different
    /// places and a caller that had to know which one was active would be back to guessing. The
    /// deadline is generous: this path runs in CI, where a cold GPU driver is slower than anything
    /// a developer sees, and the cost of waiting is a few seconds on a run that then exits.
    /// </remarks>
    private void WaitForCapture(string prefix, DateTime deadline)
    {
        if (Viewport.HasCapture || DateTime.UtcNow >= deadline)
        {
            WriteCaptures(prefix);
            return;
        }

        // Ask again: a frame is only produced when one is requested, and a viewport with nothing
        // changing produces none.
        Viewport.RequestCapture();

        DispatcherTimer.RunOnce(() => WaitForCapture(prefix, deadline), TimeSpan.FromMilliseconds(150));
    }

    private void WriteCaptures(string prefix)
    {
        UpdateStatus();

        int width = Math.Max(1, (int)Bounds.Width);
        int height = Math.Max(1, (int)Bounds.Height);

        using (RenderTargetBitmap shell = new(new PixelSize(width, height), new Vector(96, 96)))
        {
            shell.Render(this);
            shell.Save(prefix + "-shell.png", PngBitmapEncoderOptions.Default);
        }

        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture, $"wrote {prefix}-shell.png ({width}x{height})"));

        if (_about is not null)
        {
            int aboutWidth = Math.Max(1, (int)_about.Bounds.Width);
            int aboutHeight = Math.Max(1, (int)_about.Bounds.Height);

            using RenderTargetBitmap about = new(new PixelSize(aboutWidth, aboutHeight), new Vector(96, 96));
            about.Render(_about);
            about.Save(prefix + "-about.png", PngBitmapEncoderOptions.Default);

            Console.WriteLine(string.Create(
                CultureInfo.InvariantCulture, $"wrote {prefix}-about.png ({aboutWidth}x{aboutHeight})"));
        }

        if (_help is not null)
        {
            int helpWidth = Math.Max(1, (int)_help.Bounds.Width);
            int helpHeight = Math.Max(1, (int)_help.Bounds.Height);

            using RenderTargetBitmap help = new(new PixelSize(helpWidth, helpHeight), new Vector(96, 96));
            help.Render(_help);
            help.Save(prefix + "-help.png", PngBitmapEncoderOptions.Default);

            Console.WriteLine(string.Create(
                CultureInfo.InvariantCulture,
                $"wrote {prefix}-help.png ({helpWidth}x{helpHeight}); topic {_help.CurrentTopicId}"));
        }

        if (_packages is not null)
        {
            int packagesWidth = Math.Max(1, (int)_packages.Bounds.Width);
            int packagesHeight = Math.Max(1, (int)_packages.Bounds.Height);

            using RenderTargetBitmap packages = new(
                new PixelSize(packagesWidth, packagesHeight), new Vector(96, 96));
            packages.Render(_packages);
            packages.Save(prefix + "-packages.png", PngBitmapEncoderOptions.Default);

            Console.WriteLine(string.Create(
                CultureInfo.InvariantCulture,
                $"wrote {prefix}-packages.png ({packagesWidth}x{packagesHeight})"));
        }

        byte[]? pixels = Viewport.TakeCapture(out int glWidth, out int glHeight);
        if (pixels is null)
        {
            // Print the status here too. This is the one case where a reader most needs to know
            // what the viewport thought it was doing, and it was the one case that did not say:
            // the status line came after the image was written, so the failure path skipped it.
            Console.WriteLine("no viewport read-back: neither backend produced a frame.");
            Console.WriteLine(string.Create(
                CultureInfo.InvariantCulture, $"viewport status: {Viewport.Status ?? "no GL callback ran"}"));
            Console.WriteLine(string.Create(
                CultureInfo.InvariantCulture,
                $"software presenting: {Viewport.IsSoftwarePresenting}"));

            Close();
            return;
        }

        using (WriteableBitmap viewport = new(
            new PixelSize(glWidth, glHeight), new Vector(96, 96), PixelFormat.Rgba8888, AlphaFormat.Opaque))
        {
            using (ILockedFramebuffer buffer = viewport.Lock())
            {
                // TakeCapture normalises to top-down rows whichever backend drew the frame, so
                // there is nothing to flip here. It used to flip unconditionally, which was
                // right for GL and would have silently inverted every software capture.
                for (int row = 0; row < glHeight; row++)
                {
                    Marshal.Copy(pixels, row * glWidth * 4, buffer.Address + (row * buffer.RowBytes), glWidth * 4);
                }
            }

            viewport.Save(prefix + "-viewport.png", PngBitmapEncoderOptions.Default);
        }

        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"wrote {prefix}-viewport.png ({glWidth}x{glHeight}); {DescribePixels(pixels)}"));
        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture, $"viewport status: {Viewport.Status}"));

        Close();
    }

    /// <summary>
    /// Summarises a read-back so the console alone can distinguish "drew a scene" from "cleared to
    /// one colour" and from "drew nothing at all".
    /// </summary>
    /// <param name="rgba">The read-back pixels.</param>
    /// <returns>A one-line description.</returns>
    private static string DescribePixels(byte[] rgba)
    {
        System.Collections.Generic.HashSet<int> distinct = [];
        long luminanceTotal = 0;
        int samples = 0;

        for (int i = 0; i + 3 < rgba.Length; i += 4)
        {
            distinct.Add((rgba[i] << 16) | (rgba[i + 1] << 8) | rgba[i + 2]);
            luminanceTotal += (rgba[i] * 2) + (rgba[i + 1] * 5) + rgba[i + 2];
            samples++;

            if (distinct.Count > 20000)
            {
                break;
            }
        }

        double mean = samples == 0 ? 0 : luminanceTotal / (double)samples / 8.0;
        return string.Create(
            CultureInfo.InvariantCulture,
            $"{distinct.Count} distinct colours, mean luminance {mean:F1}/255");
    }

    private void OnZoomToFit(object? sender, RoutedEventArgs e)
    {
        Canvas.ZoomToFit();
        UpdateStatus();
    }

    private void OnFrameViewport(object? sender, RoutedEventArgs e) => Viewport.ZoomToFit();

    private void OnLoadSynthetic(object? sender, RoutedEventArgs e) => LoadSynthetic(2000);

    private void OnLoadDemo(object? sender, RoutedEventArgs e) => Model?.LoadDemo();

    private void OnLoadCurves(object? sender, RoutedEventArgs e) => Model?.LoadCurves();

    private void OnLoadSurfaces(object? sender, RoutedEventArgs e) => Model?.LoadSurfaces();

    private void OnLoadSolids(object? sender, RoutedEventArgs e) => Model?.LoadSolids();

    private void LoadSynthetic(int nodeCount) => Model?.LoadSynthetic(nodeCount);

    private void UpdateStatus()
    {
        if (Model is not { } model)
        {
            return;
        }

        model.ViewportStatusText = Viewport.Status ?? "Waiting for the OpenGL context.";
    }

    /// <summary>
    /// Drives a fixed pan-and-zoom cycle for a set number of compositor frames, then prints the
    /// distribution and exits.
    /// </summary>
    /// <param name="frames">How many frames to run, including a warm-up.</param>
    /// <remarks>
    /// The cycle is deterministic — a sinusoidal pan across roughly a screen width and a zoom
    /// sweep between 25% and 110% — so two runs are comparable and a regression is a number rather
    /// than an impression. The first sixth of the run is discarded: it contains JIT, the first
    /// text layout of every distinct node title and the first spatial-index build, none of which
    /// recur.
    /// </remarks>
    private void StartBenchmark(int frames)
    {
        if (_benchmarkStarted)
        {
            return;
        }

        _benchmarkStarted = true;
        _benchmarkFrames = Math.Max(60, frames);
        _framesRun = 0;
        _peakVisibleNodes = 0;

        // Give the canvas the whole window. Measuring it inside a third of the centre column
        // would produce a flattering number for the wrong reason: a smaller viewport culls more,
        // and the claim being tested is about how many nodes can be ON SCREEN at 60 fps.
        WorkspaceLayout canvasOnly = WorkspaceLayout.Default;
        canvasOnly.SetVisible(WorkspacePane.Library, false);
        canvasOnly.SetVisible(WorkspacePane.Inspector, false);
        canvasOnly.SetVisible(WorkspacePane.Viewport, false);
        _dock.Apply(canvasOnly);

        _benchmarkBounds = Canvas.Graph.ComputeBounds();
        _wallClock.Restart();
        RequestAnimationFrame(OnBenchmarkFrame);
    }

    private void OnBenchmarkFrame(TimeSpan _)
    {
        _framesRun++;

        // A deterministic sweep: three zoom cycles between 30% and 90%, and a centre that travels
        // twice around the graph, so every frame has the canvas full of nodes and the run covers
        // both sides of every level-of-detail threshold. Two runs are therefore comparable and a
        // regression is a number rather than an impression.
        double phase = _framesRun / (double)_benchmarkFrames;
        double zoom = Options.BenchmarkZoom > 0
            ? Options.BenchmarkZoom
            : 0.30 + (0.60 * (0.5 - (0.5 * Math.Cos(phase * Math.Tau * 3))));
        double centreX = _benchmarkBounds.MinX + (_benchmarkBounds.Width * (0.5 + (0.35 * Math.Sin(phase * Math.Tau * 2))));
        double centreY = _benchmarkBounds.MinY + (_benchmarkBounds.Height * (0.5 + (0.35 * Math.Cos(phase * Math.Tau * 2))));

        Canvas.Transform.Zoom = zoom;
        Canvas.Transform.OffsetX = centreX - (Canvas.Bounds.Width / (2 * zoom));
        Canvas.Transform.OffsetY = centreY - (Canvas.Bounds.Height / (2 * zoom));
        Canvas.InvalidateVisual();

        int warmUp = _benchmarkFrames / 6;
        if (_framesRun == warmUp)
        {
            // Discard the warm-up: it contains JIT, the first text layout of every distinct node
            // title and the first spatial-index build, none of which recur.
            Canvas.Frames.Reset();
            _peakVisibleNodes = 0;
            _wallClock.Restart();
        }

        _peakVisibleNodes = Math.Max(_peakVisibleNodes, Canvas.LastVisibleNodeCount);

        if (_framesRun < _benchmarkFrames)
        {
            RequestAnimationFrame(OnBenchmarkFrame);
            return;
        }

        int measured = _benchmarkFrames - warmUp;
        double wallMilliseconds = _wallClock.Elapsed.TotalMilliseconds;

        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"canvas-benchmark nodes={Canvas.Graph.Nodes.Count} wires={Canvas.Graph.Wires.Count} " +
            $"frames={measured} surface={Canvas.Bounds.Width:F0}x{Canvas.Bounds.Height:F0}"));
        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"  render pass: {Canvas.Frames.Summary()}"));
        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"  wall clock:  {wallMilliseconds / measured:F2} ms per frame, " +
            $"{measured / (wallMilliseconds / 1000.0):F0} fps"));
        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"  cull:        peak {_peakVisibleNodes} nodes on screen; last frame " +
            $"{Canvas.LastVisibleNodeCount} visible of {Canvas.LastConsideredNodeCount} considered " +
            $"at zoom {Canvas.Transform.Zoom * 100:F0}%"));
        Console.WriteLine(string.Create(
            CultureInfo.InvariantCulture,
            $"  viewport:    {Viewport.Status ?? "no GL callback ran"}"));

        Close();
    }

}
