using System;
using System.Reflection;
using Avalonia.Controls;

namespace Spark.UI.Views;

/// <summary>
/// The window shown while the application starts.
/// </summary>
/// <remarks>
/// <para>
/// It exists because startup is not instant and is not going to become instant: importing the
/// node library reflects over an assembly, and the seeded graph is evaluated before the shell can
/// draw anything. Measured end to end, <c>--screenshot</c> takes a little over two seconds from
/// process start, and the largest part of that is work the user cannot see.
/// </para>
/// <para>
/// <b>It is not shown for the measurement modes</b>, and that is not a detail — see
/// <see cref="StartupOptions.ShowSplash"/>. A splash in front of <c>--screenshot</c> would put a
/// second window in the capture, and in front of <c>--canvas-benchmark</c> it would compete with
/// the thing being measured.
/// </para>
/// </remarks>
public sealed partial class SplashWindow : Window
{
    /// <summary>Creates the splash window.</summary>
    public SplashWindow()
    {
        // Generated by Avalonia's name generator: it loads the XAML and assigns the x:Name
        // fields. Declaring one by hand shadows it and the fields stay null — the trap
        // MainWindow's constructor already documents, and this file fell into it too.
        InitializeComponent();

        VersionText.Text = DisplayVersion();
    }

    /// <summary>
    /// The version as a person would quote it.
    /// </summary>
    /// <returns>The version without build metadata, or an empty string when there is none.</returns>
    /// <remarks>
    /// MinVer computes the informational version from the nearest tag and appends the commit as
    /// build metadata, so the raw attribute reads
    /// <c>0.0.0-alpha.0.23+ed6af0787fde3d3ab60862abb48c6e547c101668</c>. Forty characters of hash
    /// on a splash screen is noise: nobody reads it and it crowds the line. Everything from the
    /// <c>+</c> is dropped, which is exactly what semantic versioning says build metadata is for —
    /// it identifies a build and carries no meaning to compare.
    /// </remarks>
    private static string DisplayVersion() => DisplayVersion(
        typeof(SplashWindow).Assembly
            .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion);

    /// <summary>Strips build metadata from an informational version.</summary>
    /// <param name="informationalVersion">The raw attribute value, which may be null.</param>
    /// <returns>The version without build metadata, or an empty string when there is none.</returns>
    /// <remarks>
    /// Public because it is the testable half of this window and there is no other way in: this
    /// assembly carries no <c>InternalsVisibleTo</c>. <c>Spark.UI</c> is not a contract project and
    /// has no public-API baseline, so ADR-0019's change control does not apply to it.
    /// </remarks>
    public static string DisplayVersion(string? informationalVersion)
    {
        if (string.IsNullOrWhiteSpace(informationalVersion))
        {
            return string.Empty;
        }

        int metadata = informationalVersion.IndexOf('+', StringComparison.Ordinal);
        return metadata < 0 ? informationalVersion : informationalVersion[..metadata];
    }
}
